### ISSUE TITLE
What dose rate space search technique to use?

### ISSUE THREAD

**Issue by koosvanamerongen** [MatthewPeterKelly/FluenceMapping#22]
We are now using CMA-ES, which seems to give decent and stable results, but sticks to its initial, constant dose rate solution more often than expected. Do we keep using CMA-ES and if so, to what extend do we want to focus on the dose rate space search? Or do we keep the dose rate to its (constant) maximum level?

**Comment by koosvanamerongen** [comment]
In any case, I believe it would be good to have the "max constant dose rate case" as a reference case so that we can quantify the effect of allowing for a variable dose rate. In terms of visualization, I believe an extra trade-off curve in the (delivery time, matching quality)-plot should suffice.

**Comment by MatthewPeterKelly** [comment]
I think that it would simplify the paper a lot to just fix the dose rate at maximum value:
- generating results would take minutes rather than hours
- we would not need to explain (and justify) the choice of CMAES over other solvers
- results and discussion sections are simpler
- we can focus more clearly on the leaf-trajectory optimization
- the CMAES optimization is not done very carefully, so the results are not great.

I propose the following:
- we drop cmaes for the main paper
- state at the beginning that we are solving a sub-problem: the dose rate is given
- use maximum (constant) dose rate for our results
- include a brief appendix where we provide one or two simple examples with cmaes 

Thoughts?

**Comment by davidcraft** [comment]
Matt, I totally agree. Let's leave it out but in the appendix let's demonstrate its use. It's new to our field and it is potentially a worthwhile search strategy for the dose rate space. Koos we can perhaps site your thesis to indicate that the dose rate space is somehow "bumpier" than the leaf trajectory space and therefore different global search techniques are needed. Somehow we need to justify/explain why we cannot use the same style of search [piecewise linear splines] in the dose rate space...

**Comment by koosvanamerongen** [comment]
I agree with both of you. Setting the dose rate to its maximum level is common practice, even though it might - and often will - lead to plans that are Pareto inefficient w.r.t. treatment quality and treatment time. So, making this simplification/approach is easily justified. Second, we can explain that the dose rate space is "nasty" and would add an outer loop in/to our method. As optimizing leaf trajectories for a given dose rate pattern is relatively computationally expensive, adding such a loop requires (too) much computational effort, Also, we could simply say that our main intension is to show how trajectory control can help in solving IMRT/VMAT problems, for which only solving the leaf trajectory problem suffices.

**Comment by MatthewPeterKelly** [comment]
It sounds like we are all in agreement:  we will drop CMAES from the paper and consider moving some of that content to the appendix. The main body of the paper will focus on examples with constant (max) dose rate, although we will point out that the algorithm works well for any arbitrary dose-rate function.
