### ISSUE TITLE
Verify equations (4) and (5), related to alpha

### ISSUE THREAD

**Issue by koosvanamerongen** [MatthewPeterKelly/FluenceMapping#34]
See David's Oct 24 email for more info

**Comment by MatthewPeterKelly** [comment]
I just went through and updated both the code and the equations. Turns out that there were small issue in both. The code now includes a simple self-check to make sure that it behaves as expected, and I've updated the equations (4) and (5) to match it on ShareLaTeX. It looks like the old convention for the $\gamma$ variable did not match the code - now it is consistent. I couldn't find it used in the result, but we will need to check that it is consistent for any future results.
